### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by mithro** [jeras/rp32#2]
* https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository
 * https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

If you don't know what license to choose, I highly recommend the Apache 2.0 license as a good permission default option that is well liked by both community and commercial interests. BSD/MIT are also common permission licenses while GPL and CC-BY-SA are common share and share alike options.

**Comment by jeras** [comment]
Done.
Thank you for pointing it out.
I was postponing this task for too long.
